{"tag": "function", "depth": 1, "time": 1721732910.5539894, "data": {"name": "connect_device", "call_args": {"uri": "ios:///http+usbmux://00008103-000C718814E3401E"}, "start_time": 1721732910.4032052, "ret": "<IOS 'http+usbmux://00008103-000C718814E3401E'>", "end_time": 1721732910.5539894}}
{"tag": "function", "depth": 1, "time": 1721732910.7509608, "data": {"name": "stop_app", "call_args": {"package": "com.zebra.soho"}, "start_time": 1721732910.563073, "ret": null, "end_time": 1721732910.7509608}}
{"tag": "function", "depth": 1, "time": 1721732911.7526116, "data": {"name": "sleep", "call_args": {"secs": 1}, "start_time": 1721732910.7509608, "ret": null, "end_time": 1721732911.7526116}}
{"tag": "function", "depth": 1, "time": 1721732912.002728, "data": {"name": "start_app", "call_args": {"package": "com.zebra.soho", "activity": null}, "start_time": 1721732911.7526116, "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\rk1277\\Desktop\\ZSB_Automation\\venv\\Lib\\site-packages\\tidevice\\_device.py\", line 501, in start_service\n    return self._unsafe_start_service(name)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\rk1277\\Desktop\\ZSB_Automation\\venv\\Lib\\site-packages\\tidevice\\_device.py\", line 520, in _unsafe_start_service\n    raise MuxServiceError(error)\ntidevice.exceptions.MuxServiceError: InvalidService\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\rk1277\\Desktop\\ZSB_Automation\\venv\\Lib\\site-packages\\airtest\\utils\\logwraper.py\", line 131, in wrapper\n    res = f(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\rk1277\\Desktop\\ZSB_Automation\\venv\\Lib\\site-packages\\airtest\\core\\api.py\", line 189, in start_app\n    G.DEVICE.start_app(package, activity)\n  File \"C:\\Users\\rk1277\\Desktop\\ZSB_Automation\\venv\\Lib\\site-packages\\airtest\\core\\ios\\ios.py\", line 49, in wrapper\n    return func(self, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\rk1277\\Desktop\\ZSB_Automation\\venv\\Lib\\site-packages\\airtest\\core\\ios\\ios.py\", line 845, in start_app\n    return TIDevice.start_app(self.udid, bundle_id)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\rk1277\\Desktop\\ZSB_Automation\\venv\\Lib\\site-packages\\airtest\\core\\ios\\ios.py\", line 69, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\rk1277\\Desktop\\ZSB_Automation\\venv\\Lib\\site-packages\\airtest\\core\\ios\\ios.py\", line 213, in start_app\n    BaseDevice(udid, Usbmux()).app_start(bundle_id=bundle_id)\n  File \"C:\\Users\\rk1277\\Desktop\\ZSB_Automation\\venv\\Lib\\site-packages\\tidevice\\_device.py\", line 718, in app_start\n    with self.connect_instruments() as ts:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\rk1277\\Desktop\\ZSB_Automation\\venv\\Lib\\site-packages\\decorator.py\", line 232, in fun\n    return caller(func, *(extras + args), **kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\rk1277\\Desktop\\ZSB_Automation\\venv\\Lib\\site-packages\\retry\\api.py\", line 73, in retry_decorator\n    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\rk1277\\Desktop\\ZSB_Automation\\venv\\Lib\\site-packages\\retry\\api.py\", line 33, in __retry_internal\n    return f()\n           ^^^\n  File \"C:\\Users\\rk1277\\Desktop\\ZSB_Automation\\venv\\Lib\\site-packages\\tidevice\\_device.py\", line 812, in connect_instruments\n    conn = self.start_service(\n           ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\rk1277\\Desktop\\ZSB_Automation\\venv\\Lib\\site-packages\\tidevice\\_device.py\", line 503, in start_service\n    self.mount_developer_image()\n  File \"C:\\Users\\rk1277\\Desktop\\ZSB_Automation\\venv\\Lib\\site-packages\\tidevice\\_device.py\", line 674, in mount_developer_image\n    raise ServiceError(\"DeveloperImage not found\")\ntidevice.exceptions.ServiceError: DeveloperImage not found\n", "end_time": 1721732912.002728}}
